### ISSUE TITLE
Some lipids are interpreted with hydroxylations 

### ISSUE THREAD

**Issue by dernesa** [lifs-tools/rgoslin#12]
Hi, 

I am trying to implement Goslin at [Lipotype](https://www.lipotype.com) to provide the shorthand2020 nomenclature to our customers. I largely works out of the box for our nomenclature, which always also provides the hydroxylations for every lipid (See below). However, for some (and only some) lipids this is misinterpreted. As a workaround, I can simply remove all 0 hydroxylations (";0") from the lipid names, however you should probably look at these special cases. 

Keep up the good work!
Mathias

``` r
library(rgoslin)
# Some lipids are interpreter with OHs 

# Correct
parseLipidName("PC O-16:1;0/16:0;0")[[1]]
#> [1] "PC O-16:1/16:0"
# with OH
parseLipidName("PC O-16:0;0/16:0;0")[[1]]
#> [1] "PC O-16:0;OH/16:0;OH"


# Correct
parseLipidName("CE 16:1;0")[[1]]
#> [1] "SE 27:1/16:1"
# with OH
parseLipidName("CE 16:0;0")[[1]]
#> [1] "SE 27:1/16:0;OH"
parseLipidName("CE 14:0;0")[[1]]
#> [1] "SE 27:1/14:0;OH"
parseLipidName("CE 17:0;0")[[1]]
#> [1] "SE 27:1/17:0;OH"

sessionInfo()
#> R version 4.1.3 (2022-03-10)
#> Platform: aarch64-apple-darwin20 (64-bit)
#> Running under: macOS Monterey 12.3.1
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] rgoslin_0.99.3
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.8.3    digest_0.6.29   withr_2.5.0     magrittr_2.0.3 
#>  [5] reprex_2.0.1    evaluate_0.15   highr_0.9       stringi_1.7.6  
#>  [9] rlang_1.0.2     cli_3.2.0       rstudioapi_0.13 fs_1.5.2       
#> [13] rmarkdown_2.13  tools_4.1.3     stringr_1.4.0   glue_1.6.2     
#> [17] xfun_0.30       yaml_2.3.5      fastmap_1.1.0   compiler_4.1.3 
#> [21] htmltools_0.5.2 knitr_1.38
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dominik-kopczynski** [comment]
Hi Mathias, thank you very much for pointing out this issue. It smells like a bug, it feels like a bug, it is a bug ;-) And since we don't like bugs, we get rid of them. Please give me some minutes.

**Comment by dominik-kopczynski** [comment]
Found the bug, but will take at least one day to fix it for rgoslin. We'll keep you informed. Cheers.

**Comment by dernesa** [comment]
Great! Thank you!

**Comment by dominik-kopczynski** [comment]
Hi Mathias, can you please pull the freshest version from the repository and try once again? Thank you Nils for fixing the problem :-)

**Comment by dernesa** [comment]
HI Dominik and Nils, 

`rgoslin::parseLipidNames()` in  rgoslin(v.0.99.12)  now produced the desired output. Thank you for the fix!

**Comment by dominik-kopczynski** [comment]
Hi Mathias, great to hear. Yes, in the new release, there is only parseLipidNames() that massively simplifies the API.
