### ISSUE TITLE
rgoslin can parse `GM1(d18:1/16:0)` but not its normalised name `GM1 18:1;O2/16:0`

### ISSUE THREAD

**Issue by JauntyJJS** [lifs-tools/rgoslin#17]
Hi,

This could be in relation to https://github.com/lifs-tools/rgoslin/issues/15

I am using the `rgoslin` version 1.0.1, install directly from github via `devtools`

It seems strange that while `rgoslin` is able to parse GM1 (and some GSL classes) in the form  `GM1(d18:1/16:0)` giving the output normalised name as `GM1 18:1;O2/16:0`, it is unable to parse GM1 in the form of its normalised name `GM1 18:1;O2/16:0`.

The same applies for GM3

``` r
library(rgoslin)

parseLipidNames("GM1(d18:1/16:0)")[["Normalized.Name"]]
#> [1] "GM1 18:1;O2/16:0"

parseLipidNames("GM1 18:1;O2/16:0")[["Normalized.Name"]]
#> Encountered an error while parsing 'GM1 18:1;O2/16:0': Expecting a single string value: [type=character; extent=4].
#> [1] NA

parseLipidNames("GM3(d18:1/16:0)")[["Normalized.Name"]]
#> [1] "GM3 18:1;O2/16:0"

parseLipidNames("GM3 18:1;O2/16:0")[["Normalized.Name"]]
#> Encountered an error while parsing 'GM3 18:1;O2/16:0': Expecting a single string value: [type=character; extent=4].
#> [1] NA

sessionInfo()
#> R version 4.2.1 (2022-06-23 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_Singapore.utf8  LC_CTYPE=English_Singapore.utf8   
#> [3] LC_MONETARY=English_Singapore.utf8 LC_NUMERIC=C                      
#> [5] LC_TIME=English_Singapore.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] rgoslin_1.0.1
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.9        rstudioapi_0.13   knitr_1.39        magrittr_2.0.3   
#>  [5] tidyselect_1.1.2  R.cache_0.16.0    R6_2.5.1          rlang_1.0.4      
#>  [9] fastmap_1.1.0     fansi_1.0.3       dplyr_1.0.9       stringr_1.4.0    
#> [13] styler_1.7.0      highr_0.9         tools_4.2.1       xfun_0.31        
#> [17] R.oo_1.25.0       utf8_1.2.2        cli_3.3.0         withr_2.5.0      
#> [21] htmltools_0.5.3   yaml_2.3.5        digest_0.6.29     tibble_3.1.8     
#> [25] lifecycle_1.0.1   purrr_0.3.4       R.utils_2.12.0    vctrs_0.4.1      
#> [29] fs_1.5.2          glue_1.6.2        evaluate_0.15     rmarkdown_2.14   
#> [33] reprex_2.0.1      stringi_1.7.8     compiler_4.2.1    pillar_1.8.0     
#> [37] generics_0.1.3    R.methodsS3_1.8.2 pkgconfig_2.0.3
```

<sup>Created on 2022-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dominik-kopczynski** [comment]
Hi, Thank you for spotting this issue. GM1 and GM3 unfortunately do not belong to the current nomenclature anymore. The head groups now have systematic names: for instance, GM1(d18:1/16:0) should be translated into Hex(3)-HexNAc-NeuAc-Cer 18:1;O2/16:0. So GM1 18:1;O2/16:0 is a technically incorrect translation. We want to update the parsers for the old nomenclatures to translate the head group names correctly. As soon as this is implemented, we will inform you.

Cheers,
Dominik

**Comment by JauntyJJS** [comment]
I see now. 
I guess GM3 should be translated to NeuAcHex2Cer.

![image](https://user-images.githubusercontent.com/9066508/181175715-c3c294d3-9b89-45e3-b533-fb736eb03038.png)

Will await for this new feature. Thank you.

**Comment by nilshoffmann** [comment]
This should be fixed in https://github.com/lifs-tools/rgoslin/commit/a49976df1ee0f4626598e0bf937b34445a068727
