### ISSUE TITLE
New names after parsing

### ISSUE THREAD

**Issue by semer94** [lifs-tools/rgoslin#19]
I am trying to analyze a lipidomics dataset using lipidr and after I create the lipidomics experiment object I get the following warning 
"Some lipid names couldn't be parsed because they don't follow the pattern 'CLS xx:x/yy:y' 
    Cer 40:1;O2, Cer 42:2;O2, HexCer 40:1;O2, LPE O-16:1, LPE O-18:1, PC O-32:1, PC O-34:1, PC O-16:0_18:2, PC O-16:1_18:1, PC O-34:3, PC O-36:1, PC O-36:2, PC O-36:4, PC O-36:5, PC O-38:4, PC O-38:5, PE O-34:2, PE O-36:3, PE O-36:5, PE O-38:5, PE O-38:7, PE O-40:7, SM 32:1;O2, SM 32:2;O2, SM 33:1;O2, SM 34:0;O2, SM 34:1;O2, SM 34:2;O2, SM 35:1;O2, SM 36:1;O2, SM 36:2;O2, SM 36:3;O2, SM 38:1;O2, SM 39:1;O2, SM 40:1;O2, SM 16:1;O2/24:1, SM 18:2;O2/22:0, SM 41:1;O2, SM 41:2;O2, SM 42:1;O2, SM 42:2;O2, SM 42:3;O2, SM 43:1;O2".

After seeing a thread of yours in bioconductor I implement the following code:

```
old_names <- rowData(d)$Molecule
new_names <- rowData(d)$clean_name %>% str_match(pattern="([\\w :-]+)(\\(\\w+\\))?")
normalized_new_names <- new_names[,2] %>% parseLipidNames(.)

lpd <- update_molecule_names(d, old_names, normalized_new_names$Normalized.Name)

rowData(lpd)$Class <- normalized_new_names$Lipid.Maps.Main.Class
rowData(lpd)$Category <- normalized_new_names$Lipid.Maps.Category
rowData(lpd)$Molecule <- normalized_new_names$Normalized.Name
rowData(lpd)$LipidSpecies <- normalized_new_names$Species.Name
rowData(lpd)$Mass <- normalized_new_names$Mass
rowData(lpd)$SumFormula <- normalized_new_names$Sum.Formula
```
Lipids seem to be parsed but I am encountering the two following issues:
1. CE class is renamed to SE 27:1, e.g. CE 16:0 renamed to SE 27:1/16:0

2.Lipids with two or more FAs keep only the first FA, e.g. PC 16:0_18:3 to PC 16:0 and TG 16:0_18:2_22:5 to TG 16:0

Could you offer some guidance, please?

**Comment by dominik-kopczynski** [comment]
Hi Semer,

I am sorry that I overlooked your issue, my apologies. Can you please tell me which rgoslin version you are using? The current version in the master branch is 1.3.2. This version should cope without problems, when you have lipid names only on species level, e.g., Cer 40:1;O2. 

1) Yes, the conversion from CE to SE 27:1 is due to the fact that in the current shorthand nomenclature [1], the lipids are annotated like this. I am also not a big fan of this change, but we want to keep the tool coherent with the latest nomenclature. Maybe they change it again in the future.

2) I would like you to test again the lipid name conversion with the current version:

```
library(rgoslin)
lipid_names = c("PA 12:0/14:0", "PC(18:0/14:0)", "SM(d16:1/12:2)", "TG 16:0_18:2_22:5", "Cer 42:2;O2")
parsed <- parseLipidNames(lipid_names)
parsed["Normalized.Name"]
#>    Normalized.Name
#> 1      PA 12:0/14:0
#> 2      PC 18:0/14:0
#> 3   SM 16:1;O2/12:2
#> 4 TG 16:0_18:2_22:5
#> 5       Cer 42:2;O2
```

If you still have problems, please feel free to drop us a line, we would appreciate that.

Cheers,
Dominik
[1] https://www.babraham.ac.uk/sites/default/files/2021-03/33037133.pdf

**Comment by semer94** [comment]
Thank you for your response!

I am using rgoslin v 1.4.0. The code you provided works fine, but I am having trouble making the lipid names properly read by lipidr after trying the following code

`lpd <- as_lipidomics_experiment(lip)

parsed <- parseLipidNames(rowData(lpd)$Molecule)

lpd <- update_molecule_names(lpd, rowData(lpd)$Molecule, parsed$Normalized.Name)`

**Comment by dominik-kopczynski** [comment]
Hi,

as far as I see, the function update_molecule_names [1] is provided by lipidr and doesn't have any return value according to this manual [1]. It changes the experiment object in-situ without creating a copy. Can you please try this code:
```
lpd <- as_lipidomics_experiment(lip)
parsed <- parseLipidNames(rowData(lpd)$Molecule)
update_molecule_names(lpd, rowData(lpd)$Molecule, parsed$Normalized.Name)  # without re-assigning lpd
```

[1] https://rdrr.io/bioc/lipidr/man/update_molecule_names.html

**Comment by semer94** [comment]
It still reads them as NAs. It is most impressive that using the code I provided in the opening thread the lipids are normally parsed (even though some of them are "cropped") and I am trying to figure out what is actually making the difference.

Thanks again Dominik!

**Comment by dominik-kopczynski** [comment]
If you want, we can have a Zoom/Skype/[other funky video tool] meeting to tackle your problem together. It is a little tough for me to give advises when I cannot reproduce the error.
