### ISSUE TITLE
Compilation fails with gcc version 13.2.0

### ISSUE THREAD

**Issue by mardam** [lifs-tools/rgoslin#22]
Hi,

I noticed that the compilation of the C++ library fails when using gcc version 13.2.0. I receive the following error message:

```
src/parser/ParserClasses.cpp:226:34: error: ‘size’ was not declared in this scope
  226 |     return Bitfield::iter(*this, size());
      |                                  ^~~~
make[1]: *** [makefile:57: src/domain/LipidClasses.cpp] Error 1
make[1]: Leaving directory '/tmp/RtmpTIGAtS/R.INSTALL81392a2ba4/rgoslin/src/cppgoslin'
make: *** [Makevars:25: sublibraries] Error 1
ERROR: compilation failed for package ‘rgoslin’
* removing ‘/usr/local/lib/R/site-library/rgoslin’
```

When I downgrade gcc to version 11.4, it compiles fine.

**Comment by dominik-kopczynski** [comment]
Thank you, on my way to fixing it.

**Comment by nilshoffmann** [comment]
@dominik-kopczynski @mardam can you verify that this has been fixed?

**Comment by dominik-kopczynski** [comment]
Sorry, I thought I had answered this issue already. Yes, the problem is solved and updated in cppgoslin and rgoslin.
