### ISSUE TITLE
LHexCer 18:1;O2 is not parseable

### ISSUE THREAD

**Issue by burlab** [lifs-tools/rgoslin#25]
Hi, 

when I run the lines below, then 1 and 2 are fine, but 3 returns `NOT_PARSEABLE`, even for 1 and 2 `LHexCer 18:1;O2` is returned in `Normalized.Name`. Is this an expected behaviour? Thank you for your time!

`1) parseLipidNames("LHexCer d18:1")`
`2) parseLipidNames("LHexCer 18:1;2")`
`3) parseLipidNames("LHexCer 18:1;O2")`

**Comment by dominik-kopczynski** [comment]
Hi Bo, Thank you for the report. On my way to search the problem.

**Comment by dominik-kopczynski** [comment]
Yuup, I found the error, we simply forgot to write LHexCer into the shorthand grammar. I fixed it and created a pull request for merging it into the main branch. Meanwhile, you can test the fixed version in the 'dev_issue_25' branch. Cheers, Dominik
PS: if there still are some problems regarding this issue, do not hesitate to reopen the bug report again.

**Comment by burlab** [comment]
Hi Dominik, thanks a lot, it works now!
