### ISSUE TITLE
Adding `LHex2Cer` and `LHex3Cer` to the grammar

### ISSUE THREAD

**Issue by burlab** [lifs-tools/rgoslin#27]
Hi Dominik, 
just realised `LHex2Cer` and `LHex3Cer` (which includes e.g. lyso-Gb3) are not in dictionary. Possible to add these species too?

**Comment by dominik-kopczynski** [comment]
Yes sir, on my way :-) Concerning the lyso-Gb3 and all its different lyso gangliosides, there is no specification ATM in the shorthand nomenclature on how to handle them. I will add the LHex2Cer and LHex3Cer and will get in touch with Gerhard L. to discuss this issue. Cheers

**Comment by dominik-kopczynski** [comment]
**LHex2Cer** and **LHex3Cer** should be now available in the development branch. Thank you very much for the feature requests :-) Cheers
