### ISSUE TITLE
Incorrect parsing of TG species names when one FA is known (e.g. TG 16:0_34:1)

### ISSUE THREAD

**Issue by burlab** [lifs-tools/rgoslin#29]
Hi Dominik,
parsing of e.g. _TG 16:0_34:1_ returns _DG 16:0_34:1_ under _Normalized.Name_ and _Molecular.Species.Name_, _DG 48:1_ as _Species.Name_ and _DG_ as lipid classes.  _TG 16:0_16:0_18:1_ and _TG 40:1_ however are parsed correctly. Thank you!

**Comment by dominik-kopczynski** [comment]
Thank you very much for the report, I could reproduce the bug. On my way to fix it.

**Comment by dominik-kopczynski** [comment]
Should be fixed now, please test in the current 'development' branch, I will send a pull request to merge in the main branch. Cheers
