### ISSUE TITLE
Possible parsing error for TAGs with one specified fatty acid

### ISSUE THREAD

**Issue by metabohaid** [lifs-tools/rgoslin#31]
Hi,

When using Rgoslin v1.6.0 for parsing  triacylglycerols where only one fatty acid is explicitly given (e.g. TG 20:1_52:1), the lipid class is recognized as diacylglycerol.

E.g. the following command will lead to the parsed results below:
` parseLipidNames("TG 20:1_52:1")`

- Normalized.Name: DG 20:1_52:1
-  **Original.Name  : TG 20:1_52:1**
- Lipid.Maps.Category :  GL 
-  Lipid.Maps.Main.Class:  DG     
-  Species.Name :  DG 72:2  
- Molecular.Species.Name:  DG 20:1_52:1  
- Total C: 72
- Total DB: 2
- Mass: 1125.101
- Sum Formula: C75H144O5
- FA1.C: 20
- FA1.DB: 1
- FA2.C: 52
- FA2.DB: 1

This behaviour is consistent across all TAGs that I have tested (ca. 500). `isValidLipidName()` is not complaining about the nomenclature, and in previous versions, the parsing has worked.
Is this a new shorthand nomenclature or maybe a bug?

**Comment by dominik-kopczynski** [comment]
Hi Metabohaid,

Thank you for your message. Yes, that was a change in the shorthand nomenclature's revision that 'TG 20:1_52:1' is now partially resolved. Since rgoslin 2.x.x, this is adapted. However, we could not yet update it in the Bioconductor repository. If you want, I can offer you a pre-compiled version of rgoslin 2 with an installation instruction. 

Cheers,
Dominik

**Comment by metabohaid** [comment]
Hi Dominik,
would be great if your could provide a pre-compiled version of rgoslin 2.

Thanks,
Mark

**Comment by dominik-kopczynski** [comment]
Hey Mark, I am done. Do you need a compiled version for a Windows or a Linux platform?

**Comment by metabohaid** [comment]
Hi Dominik,
I am using Windows, but my colleague might be interested in a Linux version. 
Thank you for help!

**Comment by dominik-kopczynski** [comment]
Hi Mark, thank you for being so patient. You can download now the manually compiled 2.0 version here [1]. Alternatively, your colleagues can clone this git repository, compile, and install the newest version on their own, the current branch is "v2_12". If they need support, please let me know. We will inform you as soon as we manage to update the Bioconductor repository.

Cheers, Dominik

[1] https://lipidomics.at/nextcloud/index.php/s/D27nizN8gzFYXtG   (NFcANt!lsat4li)
