### ISSUE TITLE
data.frame vs tibble

### ISSUE THREAD

**Issue by michaelwitting** [lifs-tools/rgoslin#4]
Hi,

one thing I found by using rgoslin is that `parseLipidName()` returns a `data.frame`, while `parseLipidNames()` returns a `tibble`. I would suggest to replace `dplyr::bind_rows(namesList)` with `do.call(rbind, list(namesList))` which returns a `data.frame`

Here an example for illustration:

```
lipidNames <- list(parseLipidName("PC 16:0_16:1"),
                   parseLipidName("PC 16:0_16:2"),
                   parseLipidName("PC 16:1_16:1"))

do.call(rbind, lipidNames)
```

**Comment by michaelwitting** [comment]
PS: Would make everything consistent :-D

**Comment by nilshoffmann** [comment]
@michaelwitting Thanks for spotting! I have adapted the code and have updated the tests to catch this in the future.
